num_beams: 1
max_length: 1024
do_sample: false
temperature: 0.7
num_return_sequences: 1

task: "multiple_choice_steps_beam"
# task: "multiple_choice_steps"
# task: "multiple_choice"


use_value: false

dataset_name: "val_random_solution_1000.jsonl" # scienceqa + [train, eval]
dataset_root: "datasets/ScienceQA"
data_subset:
data_partition: 0_499

sample_size: 
seed: 42

branch: 5
n_consistency: 7

batch_size: 50

models:
  - policy_model: "llava-v1.5-7b-policy-v0"
    value_model: 
    tag: "v_0_direct"
    run_flag: false
    use_value: false